### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by mini2fat** [franky920920/QRcode_JavaScript_Scanner#1]
Hi Franky 目前遇到多數手機(SAMSUNG/OPPO/HUAWI/ASUS)無法判讀到後置鏡頭及iphone google chrome無作用，是否有相關經驗呢?

**Comment by mini2fat** [comment]
> Hi Franky 目前遇到多數手機(SAMSUNG/OPPO/HUAWI/ASUS)無法判讀到後置鏡頭及iphone google chrome無作用，是否有相關經驗呢?

**Comment by franky920920** [comment]
嗨！雖然你關了，但是還是要問一下：是什麼原因勒，有查到了嗎？

**Comment by mini2fat** [comment]
> 嗨！雖然你關了，但是還是要問一下：是什麼原因勒，有查到了嗎？

訊息好像是自動關了。我沒查到問題，測了好幾支手機支援度並不高，我有找到其他的案例比較高支援待研究...
https://github.com/mebjas/html5-qrcode

**Comment by franky920920** [comment]
建議你檢查一下ssl或進無痕模式測測看
我這邊目前都沒問題喔
基本上出問題的話console應該會log問題下來，你把console丟出來會比較好排查
可以用remote devices 看手機的console內容：
[https://developers.google.com/web/tools/chrome-devtools/remote-debugging?hl=zh-tw](https://developers.google.com/web/tools/chrome-devtools/remote-debugging?hl=zh-tw)

**Comment by mini2fat** [comment]
好的，感謝，但主要是所有IPHONE都不行...等我結束月會有空閒再研究
